general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Droid Sans Mono Dotted for Powerline" }
bold = { family = "Droid Sans Mono Dotted for Powerline" }
italic = { family = "Droid Sans Mono Dotted for Powerline" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ mods = "Control", key = "v", action = "Paste" },
{ mods = "Control|Shift", key = "c", action = "Copy" }
]
